### ISSUE TITLE
Starting web panel error

### ISSUE THREAD

**Issue by Drarig29** [TandelK/Get5-Web-AutoInstallScript#24]
I can't make my web panel start.
I tried starting it by running `python main.py`, but I get this error:

```
Traceback (most recent call last):
  File "main.py", line 6, in <module>
    import get5
  File "/var/www/get5-web/get5/__init__.py", line 27, in <module>
    import steamid
  File "/var/www/get5-web/get5/steamid.py", line 1, in <module>
    from valve.steam.id import SteamID, SteamIDError
ImportError: No module named valve.steam.id
```

I tried to reinstall requirements with `pip install -r requirements.txt` but it still doesn't work...

**Comment by TandelK** [comment]
Yes currently there will be lot of errors as Python has ended support for 2.7 and some of the modules in requirements.txt are not working. While one of the old installation i was performing few days back i was  not able to run also the same step and found that enum in requirements.txt is not working after ending support of Python 2.7. I request you to manually remove that line from requirements.txt and try again. It might have not at all passed after enum requirements so all the others  below are not getting installed. Try to do it once manually and the script might not work as it is not  my script related but some issue related to Python 2.7 support ending from 1 Jan 2020 . If you still require help contact me on Discord. TandelK#7676

**Comment by TandelK** [comment]
Closing this issue as there is nothing can be done after EOL of Python 2.7 and found a workaround that enum in requirements is no longer working . will modify the script to remove that specific line.

**Comment by TandelK** [comment]
@Drarig29 With the current version of script it should fix the issue of enum installation.

**Comment by Drarig29** [comment]
@TandelK thank you for the effort!
But I created my own webpanel from scratch with nodejs. I didn't want to keep an old version of python and I don't like the language very much... Anyway
